[phases.build]
cmds = [
  "npm install",
  "cd /app/backend && npm install",
  "cd /app/frontend && npm install",
  "cd /app/backend && npm run build"
]

[start]
cmd = "cd /app/backend && npm start"

[variables]
NODE_ENV = "production"
NIXPACKS_PATH = ""
PORT = "3010"
