[phases.build]
cmds = [
  "npm install",
  "cd backend && npm install",
  "cd ../frontend && npm install",
  "cd .. && npm run build"
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
NIXPACKS_PATH = ""
