apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app: hosts-aggregator
    component: postgres
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: hosts_aggregator
